# Generated by Django 5.2.7 on 2025-11-03 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('article', models.CharField(max_length=100, unique=True, verbose_name='Артикул WB')),
                ('initial_quantity', models.PositiveIntegerField(default=0, verbose_name='Первоначальная закупка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото товара')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', '🟢 Приход (Дозаказ)'), ('out', '🔴 Расход (Продажа)')], max_length=3, verbose_name='Тип операции')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('date', models.DateField(verbose_name='Дата операции')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Движение товара',
                'verbose_name_plural': 'Движения товаров',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
