# Generated by Django 5.2.7 on 2025-11-11 12:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_userprofile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название кампании')),
                ('campaign_type', models.CharField(choices=[('search', '🔍 Поисковая кампания'), ('auction', '⚡ Аукцион')], max_length=10, verbose_name='Тип кампании')),
                ('status', models.CharField(choices=[('active', '🟢 Активная'), ('paused', '🟡 На паузе'), ('completed', '🔴 Завершена')], default='active', max_length=10, verbose_name='Статус')),
                ('daily_budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Дневной бюджет (руб)')),
                ('bid', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ставка (руб)')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(related_name='ad_campaigns', to='stock.product', verbose_name='Товары')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рекламная кампания',
                'verbose_name_plural': 'Рекламные кампании',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Показы')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Клики')),
                ('orders', models.PositiveIntegerField(default=0, verbose_name='Заказы')),
                ('spent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Потрачено (руб)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='stock.advertisingcampaign')),
            ],
            options={
                'verbose_name': 'Статистика кампании',
                'verbose_name_plural': 'Статистика кампаний',
                'ordering': ['-date'],
                'unique_together': {('campaign', 'date')},
            },
        ),
    ]
