# Generated by Django 5.2.7 on 2025-11-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_advertisingcampaign_campaigndailystats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisingcampaign',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='advertisingcampaign',
            name='daily_budget',
        ),
        migrations.AddField(
            model_name='campaigndailystats',
            name='cart_adds',
            field=models.PositiveIntegerField(default=0, verbose_name='Добавления в корзину'),
        ),
        migrations.AlterField(
            model_name='campaigndailystats',
            name='spent',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Затраты (руб)'),
        ),
    ]
