# Generated by Django 5.2.7 on 2025-11-22 15:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_remove_advertisingcampaign_bid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название цели')),
                ('goal_type', models.CharField(choices=[('sales', '🎯 Увеличение продаж'), ('traffic', '🚀 Улучшение рекламы'), ('conversion', '📈 Повышение конверсии'), ('brand', '🏆 Укрепление бренда'), ('profit', '💰 Увеличение прибыли'), ('other', '📝 Другая цель')], max_length=15, verbose_name='Тип цели')),
                ('description', models.TextField(blank=True, verbose_name='Описание цели')),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Целевое значение')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Текущее значение')),
                ('progress_percentage', models.PositiveIntegerField(default=0, verbose_name='Прогресс (%)')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('status', models.CharField(choices=[('active', '🟢 Активная'), ('completed', '✅ Завершена'), ('archived', '📁 В архиве')], default='active', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaigns', models.ManyToManyField(blank=True, related_name='goals', to='stock.advertisingcampaign', verbose_name='Связанные кампании')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Цель кампании',
                'verbose_name_plural': 'Цели кампаний',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок заметки')),
                ('content', models.TextField(verbose_name='Содержание заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='stock.campaigngoal')),
            ],
            options={
                'verbose_name': 'Заметка цели',
                'verbose_name_plural': 'Заметки целей',
                'ordering': ['-created_at'],
            },
        ),
    ]
