# Generated by Django 5.2.7 on 2025-12-04 18:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_campaigngoal_goalnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='Ключевое слово')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('target_position', models.PositiveIntegerField(default=0, help_text='0 означает, что цель не задана', verbose_name='Целевая позиция (0 - не задана)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='stock.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Ключевое слово',
                'verbose_name_plural': 'Ключевые слова',
                'ordering': ['keyword'],
                'unique_together': {('product', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='PositionTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='0 означает, что товар не найден в топ-200', verbose_name='Позиция в поиске')),
                ('page', models.PositiveIntegerField(default=1, help_text='На какой странице найден товар', verbose_name='Страница поиска')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время проверки')),
                ('total_found', models.PositiveIntegerField(default=0, help_text='Общее количество товаров по запросу', verbose_name='Всего найдено товаров')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='stock.productkeyword', verbose_name='Ключевое слово')),
            ],
            options={
                'verbose_name': 'Отслеживание позиции',
                'verbose_name_plural': 'Отслеживание позиций',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['keyword', 'checked_at'], name='stock_posit_keyword_0149e5_idx'), models.Index(fields=['checked_at'], name='stock_posit_checked_6ed198_idx')],
            },
        ),
    ]
