# Generated by Django 5.2.7 on 2025-12-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_productkeyword_positiontracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positiontracking',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='positiontracking',
            name='page',
        ),
        migrations.RemoveField(
            model_name='positiontracking',
            name='total_found',
        ),
        migrations.RemoveField(
            model_name='productkeyword',
            name='target_position',
        ),
        migrations.AlterField(
            model_name='positiontracking',
            name='position',
            field=models.PositiveIntegerField(help_text='0 означает, что товар не найден в поиске', verbose_name='Позиция в поиске'),
        ),
    ]
