# Generated by Django 5.2.7 on 2025-12-04 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_remove_positiontracking_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positiontracking',
            options={'ordering': ['-checked_at'], 'verbose_name': 'Позиция товара', 'verbose_name_plural': 'Позиции товаров'},
        ),
        migrations.RemoveIndex(
            model_name='positiontracking',
            name='stock_posit_keyword_0149e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='positiontracking',
            name='stock_posit_checked_6ed198_idx',
        ),
        migrations.AlterField(
            model_name='positiontracking',
            name='checked_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата проверки'),
        ),
        migrations.AlterField(
            model_name='positiontracking',
            name='position',
            field=models.PositiveIntegerField(help_text='0 = не найден', verbose_name='Позиция в поиске'),
        ),
    ]
