# Generated by Django 5.2.7 on 2025-12-04 19:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_alter_positiontracking_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productkeyword',
            options={},
        ),
        migrations.RemoveField(
            model_name='productkeyword',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productkeyword',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='productkeyword',
            name='keyword',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productkeyword',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='stock.product'),
        ),
        migrations.CreateModel(
            name='ProductPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='stock.productkeyword')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='PositionTracking',
        ),
    ]
