# Generated by Django 5.2.7 on 2025-12-04 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_productkeyword_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productposition',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='productposition',
            name='date',
        ),
        migrations.AddField(
            model_name='productposition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
